import test from "node:test";import assert from "node:assert/strict";import {PGlite} from "@electric-sql/pglite";import fs from "node:fs/promises";import {normalizeEmail,clientKey,nextDue,sendingWindow,canSend,templates,renderTemplate} from "../lib/policy";import {parseWorkbook} from "../lib/import";import {classify} from "../lib/mail";import {token,validToken} from "../lib/unsubscribe";
test("normalizes emails without collapsing distinct addresses",()=>{assert.equal(normalizeEmail(" INFO@School.IN "),"info@school.in");assert.notEqual(normalizeEmail("a+b@gmail.com"),normalizeEmail("a@gmail.com"));assert.throws(()=>normalizeEmail("foo\r\nBcc: x@example.com"));assert.equal(clientKey("Pune","St. John's"),clientKey("pune","St Johns"));});
test("72-hour sequence and IST weekday window",()=>{assert.equal(nextDue(new Date("2026-09-10T04:00Z")).toISOString(),"2026-09-13T04:00:00.000Z");assert.equal(sendingWindow(new Date("2026-09-10T04:00Z")),true);assert.equal(sendingWindow(new Date("2026-09-12T04:00Z")),false);assert.equal(sendingWindow(new Date("2026-09-10T12:00Z")),false);assert.equal(canSend({eligible:true,status:"replied",sent_count:1,next_send_at:"2020-01-01"},new Date()),false);assert.equal(canSend({eligible:true,status:"following_up",sent_count:4,next_send_at:"2020-01-01"},new Date()),false);});
test("reply classification and no invented prices in default copy",()=>{assert.equal(classify("mailer-daemon@example.com","Delivery failure","",""),"bounce");assert.equal(classify("head@school.in","Re:","Out of office","auto-replied"),"automatic");assert.equal(classify("head@school.in","","Unsubscribe me",""),"unsubscribe");assert.ok(renderTemplate(templates[0].body,{school:"Oak School",city:"Pune"},"Raghu").includes("Oak School"));assert.equal(templates.length,4);});
test("signed opt-out tokens reject tampering",()=>{process.env.UNSUBSCRIBE_SECRET="a".repeat(40);const id="11111111-1111-1111-1111-111111111111";assert.ok(validToken(id,token(id)));assert.equal(validToken(id,"b".repeat(64)),false);assert.equal(validToken("invalid",token(id)),false);});
test("the researched workbook imports exactly 105 unique contacts",async()=>{const path=process.env.LEADS_TEST_FILE;if(!path)return;const {rows,errors}=await parseWorkbook(await fs.readFile(path));assert.equal(errors.length,0,JSON.stringify(errors));assert.equal(rows.length,105);assert.equal(new Set(rows.map(r=>r.email)).size,105);for(const city of new Set(rows.map(r=>r.city)))assert.equal(rows.filter(r=>r.city===city).length,15);});
test("database sequence, duplicate protection and security",async t=>{
const pg=new PGlite();await pg.exec("create role anon; create role authenticated; create role service_role bypassrls;");
let sql=await fs.readFile(new URL("../db/schema.sql",import.meta.url),"utf8");
// Fix the business-hour clock only in this isolated database; pure policy tests cover real IST boundaries.
sql=sql.replace("localnow timestamp:=now() at time zone 'Asia/Kolkata'","localnow timestamp:=date_trunc('week',now() at time zone 'Asia/Kolkata')+interval '9 hours'");
await pg.exec(sql);
const owner="11111111-1111-1111-1111-111111111111";
const lead={school:"Test School",city:"Pune",locality:"Central",email:"office@school.in",phone:"",source_url:"https://school.in",client_key:clientKey("Pune","Test School")};
async function q(query:string,params:any[]=[]){return (await pg.query<any>(query,params)).rows;}
async function seed(){await pg.exec("truncate inbound,outbound,imports,leads cascade; update settings set sending_enabled=true,templates_approved=true,postal_address='Test address',last_sync_at=now(),last_attempt_at=null,lease_until=null,lease_owner=null,daily_limit=10;");await q("select ea_import($1::jsonb,'test.xlsx')",[JSON.stringify([lead])]);await pg.exec("update leads set eligible=true;");await q("select ea_lease($1::uuid)",[owner]);}
async function claim(){return (await q("select ea_claim($1::uuid,'example.com') as c",[owner]))[0].c;}
await t.test("re-import preserves reply and send history; alternate address conflicts",async()=>{await seed();await pg.exec("update leads set status='replied',sent_count=2,eligible=false;");const r=(await q("select ea_import($1::jsonb,'again.xlsx') as x",[JSON.stringify([lead])]))[0].x;assert.equal(r.inserted,0);assert.equal(r.duplicates,1);assert.equal((await q("select * from leads"))[0].status,"replied");const r2=(await q("select ea_import($1::jsonb,'alternate.xlsx') as x",[JSON.stringify([{...lead,email:"principal@school.in"}])]))[0].x;assert.equal(r2.rejected,1);assert.equal((await q("select count(*)::int n from leads"))[0].n,1);});
await t.test("worker lease and unique first send prevent overlapping attempts",async()=>{await seed();assert.equal((await q("select ea_lease('22222222-2222-2222-2222-222222222222') as x"))[0].x,false);const c=await claim();assert.equal(c.message.step,0);await pg.exec("update settings set last_attempt_at=null;");assert.equal(await claim(),null);});
await t.test("reply stops reserved email at final send check and event deduplicates",async()=>{await seed();const c=await claim();await q("select ea_inbound('evt','teacher@school.in','Re:',ARRAY[$1],'reply','in1','hello','')",[c.message.message_id]);const sent=(await q("select ea_begin_send($1,$2,'test','body') as x",[owner,c.message.id]))[0].x;assert.equal(sent,false);await q("select ea_inbound('evt','teacher@school.in','Re:',ARRAY[$1],'reply','in1','hello','')",[c.message.message_id]);assert.equal((await q("select count(*)::int n from inbound"))[0].n,1);assert.equal((await q("select status from leads"))[0].status,"replied");});
await t.test("exactly four accepted messages, 72-hour gap, write-off then late reply",async()=>{await seed();for(let i=0;i<4;i++){const c=await claim();assert.equal(c.message.step,i);assert.equal((await q("select ea_begin_send($1,$2,'test','body') as x",[owner,c.message.id]))[0].x,true);await q("select ea_accepted($1)",[c.message.id]);await q("select ea_accepted($1)",[c.message.id]);const l=(await q("select *,extract(epoch from(next_send_at-last_sent_at))/3600 gap from leads"))[0];assert.equal(l.sent_count,i+1);assert.equal(Number(l.gap),72);await pg.exec("update settings set last_attempt_at=null;");assert.equal(await claim(),null);if(i<3)await pg.exec("update leads set next_send_at=now()-interval '1 second';");}assert.equal((await q("select status from leads"))[0].status,"following_up");await pg.exec("update leads set next_send_at=now()-interval '1 second';select ea_housekeeping();");assert.equal((await q("select status from leads"))[0].status,"written_off");await q("select ea_inbound('late','office@school.in','Re:',ARRAY[]::text[],'reply','late1','thanks','')");assert.equal((await q("select status from leads"))[0].status,"replied");});
await t.test("uncertain SMTP results never auto-retry and reconciliation preserves reply",async()=>{await seed();const c=await claim();await q("select ea_begin_send($1,$2,'test','body')",[owner,c.message.id]);await q("select ea_uncertain($1,'timeout')",[c.message.id]);assert.equal((await q("select status from leads"))[0].status,"needs_review");await pg.exec("update settings set last_attempt_at=null");assert.equal(await claim(),null);await q("select ea_inbound('reply','office@school.in','Re:',ARRAY[$1],'reply','r1','yes','')",[c.message.message_id]);await q("select ea_accepted($1)",[c.message.id]);assert.equal((await q("select status from leads"))[0].status,"replied");});
await t.test("daily caps, fresh inbox and contact eligibility gate sends",async()=>{await seed();await pg.exec("update settings set last_sync_at=now()-interval '3 minutes'");assert.equal(await claim(),null);await pg.exec("update settings set last_sync_at=now();update leads set eligible=false;");assert.equal(await claim(),null);await pg.exec("update leads set eligible=true;update settings set daily_limit=1");const c=await claim();assert.ok(c);await pg.exec("update settings set last_attempt_at=null");await q("select ea_import($1::jsonb,'new.xlsx')",[JSON.stringify([{...lead,email:"two@school.in",school:"Two",client_key:"two"}])]);await pg.exec("update leads set eligible=true");assert.equal(await claim(),null);});
await t.test("bounce suppresses lead and pauses the campaign",async()=>{await seed();const c=await claim();await q("select ea_inbound('bounce','mailer-daemon@titan.email','Delivery failure',ARRAY[$1],'bounce','b1','failed','office@school.in')",[c.message.message_id]);assert.equal((await q("select status from leads"))[0].status,"bounced");assert.equal((await q("select sending_enabled from settings"))[0].sending_enabled,false);});
await t.test("anon and authenticated have no access; functions are private",async()=>{await pg.exec("set role anon");await assert.rejects(q("select * from leads"),/permission denied/);await assert.rejects(q("select ea_stats()"),/permission denied/);await pg.exec("reset role;set role authenticated");await assert.rejects(q("select * from outbound"),/permission denied/);await pg.exec("reset role");assert.equal((await q("select count(*)::int n from pg_class where relname in ('leads','outbound','inbound','settings','mail_cursors','imports') and relrowsecurity"))[0].n,6);});
await pg.close();
});

