"use client";
import {useEffect,useState,useCallback,useRef} from "react";
import {createClient} from "@supabase/supabase-js";
import type {Dashboard as Data,Lead,Settings} from "@/lib/model";
const supabase=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY):null;
const labels:Record<string,string>={new:"New",following_up:"Following up",replied:"Replied",written_off:"Written off",unsubscribed:"Unsubscribed",bounced:"Bounced",needs_review:"Needs review"};
const date=(v:string|null)=>v?new Date(v).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
const Icon=({name}:{name:string})=><span aria-hidden="true" className="navicon">{{Overview:"◫",Schools:"▤",Replies:"↩",Sequence:"≋",Imports:"⇧",Deliverability:"◎"}[name]||"◦"}</span>;
export default function Dashboard(){
const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState("Overview"),[session,setSession]=useState<any>(null),[ready,setReady]=useState(!supabase),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[city,setCity]=useState("All cities"),[status,setStatus]=useState("All statuses"),[selected,setSelected]=useState<string[]>([]),[note,setNote]=useState(""),[draft,setDraft]=useState<Settings|null>(null),[step,setStep]=useState(0),[loginEmail,setLoginEmail]=useState(""),[password,setPassword]=useState("");
const upload=useRef<HTMLInputElement>(null);
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const {data:subscription}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return ()=>subscription.subscription.unsubscribe();},[]);
const call=useCallback(async(path:string,body?:unknown)=>{const headers:Record<string,string>={};if(session)headers.Authorization="Bearer "+session.access_token;if(body&&!(body instanceof FormData))headers["Content-Type"]="application/json";const res=await fetch("/api/desk/"+path,{method:body?"POST":"GET",headers,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined});const value=await res.json();if(!res.ok)throw Error(value.error||"Request failed");return value;},[session]);
const refresh=useCallback(async()=>{try{const value=await call("dashboard");setData(value);setDraft(d=>d||value.settings);setError("");}catch(e){setError((e as Error).message);}},[call]);
useEffect(()=>{if(!ready||(supabase&&!session))return;void refresh();const timer=setInterval(refresh,30000);return ()=>clearInterval(timer);},[ready,session,refresh]);
async function act(path:string,body:unknown){if(data?.demo){setNotice("Demo preview only. Connect your Supabase project to use this action.");return;}setBusy(true);setError("");try{const value=await call(path,body);setNotice(value.message||value.status||"Saved");await refresh();return value;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function importFile(file?:File){if(!file)return;const form=new FormData();form.set("file",file);const r=await act("import",form);if(r){setNotice(r.inserted+" new · "+r.duplicates+" existing · "+r.rejected+" rejected");setTab("Imports");}if(upload.current)upload.current.value="";}
if(!ready)return <main className="loading">Opening outreach desk…</main>;
if(supabase&&!session)return <main className="login"><div className="brandmark">e</div><p className="eyebrow">EDUTRIP / OUTREACH DESK</p><h1>Welcome back.</h1><p>Sign in with your approved team account.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email:loginEmail,password});if(error)setError(error.message);setBusy(false);}}><label>Email<input type="email" required value={loginEmail} onChange={e=>setLoginEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Sign in</button></form>{error&&<p role="alert" className="error">{error}</p>}</main>;
const visible=(data?.leads||[]).filter(l=>(city==="All cities"||l.city===city)&&(status==="All statuses"||l.status===status)&&(l.school+" "+l.email+" "+l.city).toLowerCase().includes(query.toLowerCase()));
const chosen=visible.filter(l=>selected.includes(l.id));
const cards=[["Emails sent","sent","Accepted by Titan"],["Replies received","replies","Matched human replies"],["Following up","following_up","Active school conversations"],["Written off","written_off","Sequence finished"]];
function badge(l:Lead){return <span className={"badge "+l.status}>{labels[l.status]}</span>}
function leadsTable(list:Lead[],compact=false){return <div className="table-scroll"><table><thead><tr>{!compact&&<th><input aria-label="Select visible new leads" type="checkbox" checked={!!list.filter(l=>l.status==="new").length&&list.filter(l=>l.status==="new").every(l=>selected.includes(l.id))} onChange={e=>setSelected(e.target.checked?list.filter(l=>l.status==="new").map(l=>l.id):[])}/></th>}<th>School</th><th>City</th><th>Status</th><th>Sequence</th><th>Due after · IST</th>{!compact&&<th>Actions</th>}</tr></thead><tbody>{list.map(l=><tr key={l.id}>{!compact&&<td><input aria-label={"Select "+l.school} type="checkbox" disabled={l.status!=="new"} checked={selected.includes(l.id)} onChange={e=>setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id))}/></td>}<td><strong>{l.school}</strong><small>{l.email}</small>{!compact&&<small>{l.locality} {l.source_url&&<a href={l.source_url} target="_blank" rel="noreferrer">Source ↗</a>}</small>}</td><td>{l.city}</td><td>{badge(l)}{l.status==="new"&&<small>{l.eligible?"Ready to send":"Contact basis needed"}</small>}</td><td><div className="steps" aria-label={l.sent_count+" of 4 emails sent"}>{[0,1,2,3].map(i=><span key={i} className={i<l.sent_count?"done":""}/>)}</div><small>{l.sent_count} of 4 sent</small></td><td>{l.status==="following_up"||l.eligible?date(l.next_send_at):"—"}{l.sent_count===4&&l.status==="following_up"&&<small>Close if no reply</small>}</td>{!compact&&<td><button className="textbtn" disabled={busy||["unsubscribed","bounced"].includes(l.status)} onClick={()=>act("stop",{id:l.id,status:"unsubscribed"})}>Stop</button><button className="textbtn" disabled={busy||l.status==="replied"} onClick={()=>act("stop",{id:l.id,status:"replied"})}>Mark replied</button></td>}</tr>)}</tbody></table>{!list.length&&<div className="empty">No schools in this view.</div>}</div>}
return <div className="shell"><aside><div className="brand"><span className="brandmark">e</span><div>edutrip<span>OUTREACH DESK</span></div></div><div className="workspace"><span className="avatar">EI</span><div>Edutrip India<small>School partnerships</small></div></div><p className="navlabel">WORKSPACE</p><nav>{["Overview","Schools","Replies","Sequence","Imports","Deliverability"].map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}><Icon name={t}/>{t}{t==="Replies"&&!!data?.stats.replies&&<span className="navcount">{data.stats.replies}</span>}</button>)}</nav><div className="sidebottom"><div className="smallstatus"><span className="dot amber"/>{data?.settings.sending_enabled?"Agent enabled":"Agent paused"}</div><p>One introduction.<br/>Three thoughtful follow-ups.</p>{session&&<button className="textbtn" onClick={()=>supabase?.auth.signOut()}>Sign out</button>}</div></aside>
<main><header><div><span className="breadcrumb">Workspace</span><span className="slash">/</span>{tab}</div><span className="headerdate">{new Date().toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}<span className="avatar">EI</span></span></header>
<div className="content">{data?.demo&&<div className="demo-banner">DEMO PREVIEW <span>Illustrative schools and metrics. Connect your new Supabase project to start with your researched leads.</span></div>}
<div className="pagehead"><div><p className="eyebrow">SCHOOL PARTNERSHIPS</p><h1>{tab==="Overview"?"Every conversation, in view.":tab==="Schools"?"Your next school partnerships.":tab==="Replies"?"The conversation is yours.":tab==="Sequence"?"A little persistence. A clear stopping point.":tab==="Imports"?"Fresh leads. History intact.":"Earn a place in the inbox."}</h1><p>{tab==="Overview"?"A clear picture of outreach, follow-ups and schools ready for your attention.":tab==="Schools"?"Review contact details and permission before starting a school’s sequence.":tab==="Replies"?"Any matched reply stops the sequence, including automatic responses.":tab==="Sequence"?"One introduction and three follow-ups, at least 72 hours apart.":tab==="Imports"?"Refresh your Excel every alternate day. Existing clients keep their history.":"Conservative sending controls, clear identity and immediate opt-outs."}</p></div><div className="actions"><button className="secondary" disabled={busy||!data} onClick={()=>act("sync",{})}>Check replies</button><button disabled={busy} onClick={()=>upload.current?.click()}>＋ Import Excel</button><input ref={upload} type="file" accept=".xlsx" hidden onChange={e=>importFile(e.target.files?.[0])}/></div></div>
{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}<button className="textbtn" onClick={()=>setNotice("")}>Dismiss</button></div>}
{!data?<div className="empty">{error?"Connect the database and retry.":"Loading your outreach desk…"}</div>:<>
{tab==="Overview"&&<><div className="metrics">{cards.map(([label,key,desc])=><section className="metric" key={key}><div>{label}<span className="metric-icon">{key==="sent"?"↗":key==="replies"?"↩":key==="following_up"?"◷":"✓"}</span></div><strong>{data.stats[key]||0}</strong><small>{desc}</small></section>)}</div><div className="overview-grid"><section className="panel"><div className="panelhead"><div><h2>Outreach journey</h2><p>Four emails. No response means we stop.</p></div><span className="pill">72-hour interval</span></div><div className="journey">{["Introduction","Follow-up 1","Follow-up 2","Final follow-up"].map((label,i)=><div key={label}><span className="journey-number">{String(i+1).padStart(2,"0")}</span><strong>{label}</strong><small>{i===0?"First eligible slot":"72 hours after last send"}</small></div>)}</div><div className="panelnote">Replies stop all future emails. After the final follow-up, allow 72 hours for a response before closing.</div></section><section className="panel attention"><p className="eyebrow">NEEDS YOUR ATTENTION</p><h2>{data.stats.review} schools to review</h2><p>Confirm contact eligibility and resolve uncertain delivery before these schools can move ahead.</p><button className="secondary" onClick={()=>{setTab("Schools");setStatus("All statuses")}}>Review schools →</button></section></div><section className="panel"><div className="panelhead"><div><h2>School pipeline</h2><p>The latest schools in your workspace</p></div><button className="textbtn" onClick={()=>setTab("Schools")}>View all schools →</button></div>{leadsTable(data.leads.slice(0,7),true)}</section><div className="healthrow"><span><span className="dot green"/>{data.setup.database?"Database connected":"Database awaiting setup"}</span><span>Last reply sync: {date(data.settings.last_sync_at)}</span><span>Sent today: {data.stats.sent_today} / {data.settings.daily_limit}</span></div></>}
{tab==="Schools"&&<><div className="filters"><input placeholder="Search school, email or city" aria-label="Search schools" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="City" value={city} onChange={e=>setCity(e.target.value)}><option>All cities</option>{[...new Set(data.leads.map(l=>l.city))].sort().map(c=><option key={c}>{c}</option>)}</select><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><span>{visible.length} shown · {data.stats.leads} total</span></div>{chosen.length>0&&<div className="qualification"><strong>{chosen.length} selected</strong><input aria-label="Contact permission basis" placeholder="Record permission or other provider-permitted contact basis" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={busy||note.trim().length<10} onClick={async()=>{const r=await act("qualify",{ids:chosen.map(l=>l.id),note});if(r){setSelected([]);setNote("");}}}>Qualify selected</button></div>}<section className="panel">{leadsTable(visible)}</section><p className="footnote">Shows up to 1,000 latest leads. Import status columns never reset the agent’s history.</p></>}
{tab==="Replies"&&<section className="panel"><div className="panelhead"><h2>Reply inbox</h2><span className="pill">Handled by you</span></div>{!data.replies.length?<div className="empty">No replies yet. Matched replies appear here after the next mailbox check.</div>:data.replies.map(r=><article className="reply" key={r.id}><div><strong>{r.from_email}</strong><span className="badge">{r.kind}</span><small>{date(r.received_at)}</small></div><h3>{r.subject||"(No subject)"}</h3><p className="mailtext">{r.excerpt}</p>{r.kind==="unmatched"&&<p>Could not match automatically. Review the mailbox and mark the relevant school replied if needed.</p>}</article>)}</section>}
{tab==="Sequence"&&draft&&<div className="sequence-layout"><section className="panel"><div className="panelhead"><h2>Email sequence</h2><span className="pill">4 messages maximum</span></div><div className="tabs">{draft.templates.map((t,i)=><button className={step===i?"selected":""} key={i} onClick={()=>setStep(i)}>{i===0?"Introduction":"Follow-up "+i}</button>)}</div><div className="editor"><label>Subject<input value={draft.templates[step]?.subject||""} onChange={e=>setDraft({...draft,templates:draft.templates.map((t,i)=>i===step?{...t,subject:e.target.value}:t)})}/></label><label>Email body<textarea rows={15} value={draft.templates[step]?.body||""} onChange={e=>setDraft({...draft,templates:draft.templates.map((t,i)=>i===step?{...t,body:e.target.value}:t)})}/></label><small>Personalization: {"{{school}}"} · {"{{city}}"} · {"{{sender}}"}<br/>Postal address and unsubscribe link are appended automatically.</small></div></section><section className="panel editor"><h2>Sender & controls</h2><label>Sender display name<input value={draft.sender_name} onChange={e=>setDraft({...draft,sender_name:e.target.value})}/></label><label>Business postal address<textarea rows={3} placeholder="Enter the real business mailing address" value={draft.postal_address} onChange={e=>setDraft({...draft,postal_address:e.target.value})}/></label><label>Total daily limit<input type="number" min={1} max={50} value={draft.daily_limit} onChange={e=>setDraft({...draft,daily_limit:Number(e.target.value)})}/></label><label>Minimum minutes between emails<input type="number" min={30} max={240} value={draft.min_gap_minutes} onChange={e=>setDraft({...draft,min_gap_minutes:Number(e.target.value)})}/></label><p>Includes first emails and follow-ups. Monday–Friday, 10 am–4 pm IST; at least 30 minutes between sends.</p><button disabled={busy} onClick={()=>act("settings",draft)}>Save templates & schedule</button><hr/><h3>{data.settings.sending_enabled?"Sending enabled":"Sending paused"}</h3><p>Saving template or schedule changes pauses the agent. Resume only when the sender and lead checks are complete.</p><button className="secondary" disabled={busy} onClick={()=>act("toggle",{enabled:!data.settings.sending_enabled})}>{data.settings.sending_enabled?"Pause sending":"Enable sending"}</button></section></div>}
{tab==="Imports"&&<><section className="panel importbox"><div className="uploadicon">⇧</div><h2>Bring your updated school list.</h2><p>Upload .xlsx files up to 4 MB and 2,000 rows.<br/>Required columns: School, City, Email.</p><button onClick={()=>upload.current?.click()} disabled={busy}>Choose Excel file</button><p className="footnote">Metadata updates are safe. Sent counts, replies and suppression are kept in the database.</p></section><section className="panel"><div className="panelhead"><h2>Import history</h2><span>Latest 20 uploads</span></div>{!data.imports.length?<div className="empty">Your first import will appear here.</div>:data.imports.map(i=><article className="reply" key={i.id}><strong>{i.filename}</strong><small>{date(i.created_at)} · {i.inserted} new · {i.duplicates} existing · {i.rejected} rejected</small>{i.issues?.length>0&&<details><summary>Review rejected rows</summary>{i.issues.map((x:any,n:number)=><p key={n}>{x.row?"Row "+x.row:x.email}: {x.reason}</p>)}</details>}</article>)}</section></>}
{tab==="Deliverability"&&<><div className="overview-grid"><section className="panel editor"><h2>Sending health</h2><dl><dt>Database</dt><dd>{data.setup.database?"Connected":"Awaiting project"}</dd><dt>Titan credentials</dt><dd>{data.setup.mail?"Configured":"Awaiting setup"}</dd><dt>Live sending gate</dt><dd>{data.setup.live?"Enabled in deployment":"Disabled"}</dd><dt>Reply sync</dt><dd>{date(data.settings.last_sync_at)}</dd><dt>Last worker run</dt><dd>{date(data.settings.last_run_at)}</dd><dt>Daily limit</dt><dd>{data.settings.daily_limit} emails</dd></dl>{data.settings.last_error&&<p className="error">{data.settings.last_error}</p>}</section><section className="panel editor"><h2>Protect the domain</h2><ul className="checklist"><li>Configure aligned SPF, DKIM and DMARC for the sender domain.</li><li>Use a provisioned reply alias and monitor its destination mailbox.</li><li>Qualify contact permission. A published email is not proof of consent.</li><li>Start at 5 emails per day. Increase only after five healthy sending days.</li><li>Keep emails short, specific and free of tracking pixels and attachments.</li><li>Stop immediately on replies, bounces and opt-outs.</li></ul><p>No configuration guarantees inbox placement. Review Titan’s acceptable-use rules before enabling a campaign.</p><a href="https://support.titan.email/hc/en-us/articles/900000775226-Titan-Acceptable-Use-Policy" target="_blank" rel="noreferrer">Titan acceptable-use policy ↗</a></section></div><section className="panel"><div className="panelhead"><h2>Delivery records</h2><span>Latest 100 attempts</span></div>{!data.messages.length?<div className="empty">No messages have been sent.</div>:<div className="table-scroll"><table><thead><tr><th>Message</th><th>Step</th><th>State</th><th>Time · IST</th><th>Review</th></tr></thead><tbody>{data.messages.map(m=><tr key={m.id}><td>{m.subject}<small>{m.message_id}</small></td><td>{m.step===0?"Introduction":"Follow-up "+m.step}</td><td><span className="badge">{m.state}</span></td><td>{date(m.sent_at||m.created_at)}</td><td>{["uncertain","sending"].includes(m.state)&&<button className="secondary" disabled={busy} onClick={()=>act("reconcile",{id:m.id})}>Check Titan Sent</button>}<small>{m.error}</small></td></tr>)}</tbody></table></div>}</section></>}
</>}</div><footer>Edutrip India <span>Thoughtful outreach. Meaningful learning.</span></footer></main></div>;
}

